### ISSUE TITLE
PHP Error on Activate

### ISSUE THREAD

**Issue by wjramos** [Giuseppe-Mazzapica/GMRejectNotify#2]
( ! ) Parse error: syntax error, unexpected '[' in /wp-content/plugins/GMRejectNotify/src/Plugin.php on line 154

**Comment by Giuseppe-Mazzapica** [comment]
As stated in the readme this plugin requires PHP 5.4+. The error you get happen on PHP 5.3.

Note that 5.3 is noto supported anymore, it doesn't receives updates
