### ISSUE TITLE
Custom post type support

### ISSUE THREAD

**Issue by YousefRahimi** [Giuseppe-Mazzapica/GMRejectNotify#3]
Hi, There is no custom post type support for your plugin. Is there anyway you can help me about that?

**Comment by Giuseppe-Mazzapica** [comment]
Hi @YousefRahimi 
no, currently there is no support for custo post types.

Editing the method [`Plugin::regularShould()`](https://github.com/Giuseppe-Mazzapica/GMRejectNotify/blob/master/src/Plugin.php#L199-L221) you see that the plugin activate only for standard post type.

In fact at [line 202](https://github.com/Giuseppe-Mazzapica/GMRejectNotify/blob/master/src/Plugin.php#L202) it checks that `get_current_screen()->id` is equal to `"post"` and at line [213](https://github.com/Giuseppe-Mazzapica/GMRejectNotify/blob/master/src/Plugin.php#L213) that  `get_current_screen()->id` is equal to `"edit-post"`.

For a CPT with slug "book" that values are `"book"` and `"edit-book"`.

So you can edit those 2 lines to make it works for CPT. It would be nice adding a filter to make it configurable.

If you manage to do that, please send me a PR.

Thanks.

**Comment by YousefRahimi** [comment]
Yeah, thanks @Giuseppe-Mazzapica. I've figured it out already about a day ago I suppose. Actually there should be an edit at line 167 too. But as you said, it's kind of hard-coded. I'll make something configurable as a setting to the plugin and I'll let you know. And again, thanks :)
